name: dscript

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - pip=20.0
  - cudatoolkit=11.8
  - python=3.8
  - pytorch=2.0.0
  - biopython
  - h5py
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - setuptools
  - tqdm
